apiVersion: v1
kind: ConfigMap
data:
  config: |-
    agent.application_code=spring-petclinic-rest-vet
    agent.sample_n_per_3_secs=-1
    agent.span_limit_per_segment=300
    agent.ignore_suffix=.jpg,.jpeg,.js,.css,.png,.bmp,.gif,.ico,.mp3,.mp4,.html,.svg
    agent.is_open_debugging_class = false
    collector.servers=skywalking-collector:10800
    logging.level=DEBUG
metadata:
  name: skywalking-agent-spring-petclinic-rest-vet-config
  labels:
    name: skywalking-agent-spring-petclinic-rest-vet-config
  namespace: skywalking
  
