apiVersion: v1
kind: ConfigMap
metadata:
  name: skywalking-collector-config
  labels:
    name: skywalking-collector-config
  namespace: skywalking
data:
  config: |-
    ---
    naming:
      jetty:
        host: 0.0.0.0
        port: 10800
        contextPath: /
    cache:
      caffeine:
    remote:
      gRPC:
        host: localhost
        port: 11800
    agent_gRPC:
      gRPC:
        host: skywalking-collector
        port: 11800
        authentication: PPzfXEGMEbZ6NN7b
    agent_jetty:
      jetty:
        host: localhost
        port: 12800
        contextPath: /
    analysis_register:
      default:
    analysis_jvm:
      default:
    analysis_segment_parser:
      default:
        bufferFilePath: ../buffer/
        bufferOffsetMaxFileSize: 10M
        bufferSegmentMaxFileSize: 500M
        bufferFileCleanWhenRestart: true
    ui:
      jetty:
        host: skywalking-collector
        port: 12800
        contextPath: /
    storage:
      elasticsearch:
        clusterName: docker-cluster
        clusterTransportSniffer: true
        clusterNodes: elasticsearch:9300
        indexShardsNumber: 2
        indexReplicasNumber: 0
        highPerformanceMode: true
        ttl: 7
    configuration:
      default:
        namespace: petshop
        applicationApdexThreshold: 2000
        serviceErrorRateThreshold: 10.00
        serviceAverageResponseTimeThreshold: 2000
        instanceErrorRateThreshold: 10.00
        instanceAverageResponseTimeThreshold: 2000
        applicationErrorRateThreshold: 10.00
        applicationAverageResponseTimeThreshold: 2000
        thermodynamicResponseTimeStep: 50
        thermodynamicCountOfResponseTimeSteps: 40
  log4j: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <!--
      ~ Licensed to the Apache Software Foundation (ASF) under one or more
      ~ contributor license agreements.  See the NOTICE file distributed with
      ~ this work for additional information regarding copyright ownership.
      ~ The ASF licenses this file to You under the Apache License, Version 2.0
      ~ (the "License"); you may not use this file except in compliance with
      ~ the License.  You may obtain a copy of the License at
      ~
      ~     http://www.apache.org/licenses/LICENSE-2.0
      ~
      ~ Unless required by applicable law or agreed to in writing, software
      ~ distributed under the License is distributed on an "AS IS" BASIS,
      ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      ~ See the License for the specific language governing permissions and
      ~ limitations under the License.
      ~
      -->
    
    <Configuration status="info">
        <Properties>
            <Property name="log-path">${sys:collector.logDir}</Property>
        </Properties>
        <Appenders>
            <RollingFile name="RollingFile" fileName="${log-path}/skywalking-collector-server.log"
                         filePattern="${log-path}/skywalking-collector-server-%d{yyyy-MM-dd}-%i.log" >
                <PatternLayout>
                    <pattern>%d - %c -%-4r [%t] %-5p %x - %m%n</pattern>
                </PatternLayout>
                <Policies>
                    <SizeBasedTriggeringPolicy size="102400KB" />
                </Policies>
                <DefaultRolloverStrategy max="30"/>
            </RollingFile>
        </Appenders>
        <Loggers>
            <logger name="org.eclipse.jetty" level="INFO"/>
            <logger name="org.apache.zookeeper" level="INFO"/>
            <logger name="org.apache.skywalking.apm.collector.agent.grpc.provider.handler.JVMMetricsServiceHandler" level="INFO"/>
            <logger name="org.apache.skywalking.apm.collector.analysis.worker.timer.PersistenceTimer" level="INFO"/>
            <logger name="io.grpc.netty" level="INFO"/>
            <Root level="info">
                <AppenderRef ref="RollingFile"/>
            </Root>
        </Loggers>
    </Configuration>
    
