---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: petclinic-mysql
    labels:
      app: petclinic-mysql
    namespace: skywalking
  spec:
    template:
      metadata:
        labels:
          app: petclinic-mysql
      spec:
        containers:
        - image: "mysql:5.7.8"
          name: petclinic-mysql
          imagePullPolicy: Always
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: petclinic
          - name: MYSQL_DATABASE
            value: petclinic
          ports:
          - containerPort: 3306
        imagePullSecrets:
        - name: registrykey
- apiVersion: v1
  kind: Service
  metadata:
    name: petclinic-mysql
    labels:
      app: petclinic-mysql
    namespace: skywalking
  spec:
    clusterIP: None
    selector:
      app: petclinic-mysql
    ports:
    - port: 3306
      name: petclinic-mysql

