---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: skywalking-petclinick
    labels:
      app: skywalking-petclinick
    namespace: skywalking
  spec:
    template:
      metadata:
        labels:
          app: skywalking-petclinick
      spec:
        containers:
        - image: akozichev/skywalking-petclinick:latest
          name: skywalking-petclinick
          imagePullPolicy: Always
          volumeMounts:
          - mountPath:  /usr/local/petclinic/agent/config
            name: skywalking-agent-petclinic-config
          ports:
          - containerPort: 8010
        volumes:
        - name: skywalking-agent-petclinic-config
          configMap:
            name: skywalking-agent-petclinic-config
            items:
            - key: config
              path:  agent.config
        imagePullSecrets:
        - name: registrykey
- apiVersion: v1
  kind: Service
  metadata:
    name: skywalking-petclinick
    labels:
      app: skywalking-petclinick
    namespace: skywalking
  spec:
    type: NodePort
    selector:
      app: skywalking-petclinick
    ports:
    - port: 8010
      name: skywalking-petclinick

