---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: skywalking-spring-petclinic-rest-vet
    labels:
      app: skywalking-spring-petclinic-rest-vet
    namespace: skywalking
  spec:
    template:
      metadata:
        labels:
          app: skywalking-spring-petclinic-rest-vet
      spec:
        containers:
        - image: akozichev/skywalking-spring-petclinic-rest-vet:latest
          name: skywalking-spring-petclinic-rest-vet
          imagePullPolicy: Always
          volumeMounts:
          - mountPath:  /usr/local/petshop/spring-petclinic-rest-vet/agent/config
            name: skywalking-agent-spring-petclinic-rest-vet-config
          ports:
          - containerPort: 8004
        volumes:
        - name: skywalking-agent-spring-petclinic-rest-vet-config
          configMap:
            name: skywalking-agent-spring-petclinic-rest-vet-config
            items:
            - key: config
              path:  agent.config
        imagePullSecrets:
        - name: registrykey
- apiVersion: v1
  kind: Service
  metadata:
    name: skywalking-spring-petclinic-rest-vet
    labels:
      app: skywalking-spring-petclinic-rest-vet
    namespace: skywalking
  spec:
    type: NodePort
    selector:
      app: skywalking-spring-petclinic-rest-vet
    ports:
    - port: 8004
      name: skywalking-spring-petclinic-rest-vet

