---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: skywalking-collector
    labels:
      app: skywalking-collector
    namespace: skywalking
  spec:
    template:
      metadata:
        labels:
          app: skywalking-collector
      spec:
        containers:
        - image: akozichev/skywalking-collector:latest
          name: skywalking-collector
          imagePullPolicy: Always
          volumeMounts:
          - mountPath:  /opt/skywalking/collector/config
            name: skywalking-collector-config
          ports:
          - containerPort: 10800
          - containerPort: 11800
          - containerPort: 12800
        volumes:
        - name: skywalking-collector-config
          configMap:
            name: skywalking-collector-config
            items:
            - key: config
              path:  application.yml
            - key: log4j
              path:  log4j.xml
        imagePullSecrets:
        - name: registrykey
- apiVersion: v1
  kind: Service
  metadata:
    name: skywalking-collector
    labels:
      app: skywalking-collector
    namespace: skywalking
  spec:
    clusterIP: None
    selector:
      app: skywalking-collector
    ports:
    - port: 10800
      name: skywalking-collector
    - port: 12800
      name: skywalking-collector-ui
- apiVersion: v1
  kind: Service
  metadata:
    name: skywalking-collector-ext
    labels:
      app: skywalking-collector-ext
    namespace: skywalking
  spec:
    type: LoadBalancer
    selector:
      app: skywalking-collector
    ports:
    - port: 10800
      targetPort: 10800
      name: skywalking-collector-ext
    - port: 12800
      targetPort: 12800
      name: skywalking-collector-ui-ext
    - port: 11800
      targetPort: 11800
      name: skywalking-collector-grpc-ext

