---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: skywalking-spring-petclinic-rest-visit
    labels:
      app: skywalking-spring-petclinic-rest-visit
    namespace: skywalking
  spec:
    template:
      metadata:
        labels:
          app: skywalking-spring-petclinic-rest-visit
      spec:
        containers:
        - image: akozichev/skywalking-spring-petclinic-rest-visit:latest
          name: skywalking-spring-petclinic-rest-visit
          imagePullPolicy: Always
          volumeMounts:
          - mountPath:  /usr/local/petshop/spring-petclinic-rest-visit/agent/config
            name: skywalking-agent-spring-petclinic-rest-visit-config
          - mountPath:  /usr/local/petshop/spring-petclinic-rest-visit/config
            name: petclinic-config
          ports:
          - containerPort: 8005
        volumes:
        - name: skywalking-agent-spring-petclinic-rest-visit-config
          configMap:
            name: skywalking-agent-spring-petclinic-rest-visit-config
            items:
            - key: config
              path:  agent.config
        - name: petclinic-config
          configMap:
            name: petclinic-config
            items:
            - key: config
              path:  application.properties
        imagePullSecrets:
        - name: registrykey
- apiVersion: v1
  kind: Service
  metadata:
    name: skywalking-spring-petclinic-rest-visit
    labels:
      app: skywalking-spring-petclinic-rest-visit
    namespace: skywalking
  spec:
    type: NodePort
    selector:
      app: skywalking-spring-petclinic-rest-visit
    ports:
    - port: 8005
      name: skywalking-spring-petclinic-rest-visit

