---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: skywalking-spring-petclinic-rest-owner
    labels:
      app: skywalking-spring-petclinic-rest-owner
    namespace: skywalking
  spec:
    template:
      metadata:
        labels:
          app: skywalking-spring-petclinic-rest-owner
      spec:
        containers:
        - image: akozichev/skywalking-spring-petclinic-rest-owner:latest
          name: skywalking-spring-petclinic-rest-owner
          imagePullPolicy: Always
          volumeMounts:
          - mountPath:  /usr/local/petshop/spring-petclinic-rest-owner/agent/config
            name: skywalking-agent-spring-petclinic-rest-owner-config
          - mountPath:  /usr/local/petshop/spring-petclinic-rest-owner/config
            name: petclinic-config
          ports:
          - containerPort: 8001
        volumes:
        - name: skywalking-agent-spring-petclinic-rest-owner-config
          configMap:
            name: skywalking-agent-spring-petclinic-rest-owner-config
            items:
            - key: config
              path:  agent.config
        - name: petclinic-config
          configMap:
            name: petclinic-config
            items:
            - key: config
              path:  application.properties
        imagePullSecrets:
        - name: registrykey
- apiVersion: v1
  kind: Service
  metadata:
    name: skywalking-spring-petclinic-rest-owner
    labels:
      app: skywalking-spring-petclinic-rest-owner
    namespace: skywalking
  spec:
    type: NodePort
    selector:
      app: skywalking-spring-petclinic-rest-owner
    ports:
    - port: 8001
      name: skywalking-spring-petclinic-rest-owner

